<?php

namespace Container0JdarXb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TyPUV8NService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TyPUV8N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TyPUV8N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'productoRepository' => ['privates', 'App\\Repository\\ProductoRepository', 'getProductoRepositoryService', true],
        ], [
            'productoRepository' => 'App\\Repository\\ProductoRepository',
        ]);
    }
}
