<?php

namespace Container0JdarXb;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFabricanteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.GayI6Pf.App\Entity\Fabricante' shared service.
     *
     * @return \App\Entity\Fabricante
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.GayI6Pf": it references class "App\\Entity\\Fabricante" but no such service exists.');
    }
}
