<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRKKtZ59\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRKKtZ59/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRKKtZ59.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRKKtZ59\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRKKtZ59\App_KernelDevDebugContainer([
    'container.build_hash' => 'RKKtZ59',
    'container.build_id' => 'e6db8eb5',
    'container.build_time' => 1687418556,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRKKtZ59');
