<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0JdarXb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0JdarXb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0JdarXb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0JdarXb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0JdarXb\App_KernelDevDebugContainer([
    'container.build_hash' => '0JdarXb',
    'container.build_id' => 'bdbf15f7',
    'container.build_time' => 1687420503,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0JdarXb');
