<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAVpJRbT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAVpJRbT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAVpJRbT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAVpJRbT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAVpJRbT\App_KernelDevDebugContainer([
    'container.build_hash' => 'AVpJRbT',
    'container.build_id' => '070d86bf',
    'container.build_time' => 1687348384,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAVpJRbT');
