<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_fabricante_index' => [[], ['_controller' => 'App\\Controller\\FabricanteController::index'], [], [['text', '/fabricante']], [], [], []],
    'app_fabricante_new' => [[], ['_controller' => 'App\\Controller\\FabricanteController::new'], [], [['text', '/fabricante/new']], [], [], []],
    'app_fabricante_show' => [['id'], ['_controller' => 'App\\Controller\\FabricanteController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/fabricante']], [], [], []],
    'app_fabricante_edit' => [['id'], ['_controller' => 'App\\Controller\\FabricanteController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/fabricante']], [], [], []],
    'app_fabricante_delete' => [['id'], ['_controller' => 'App\\Controller\\FabricanteController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/fabricante']], [], [], []],
    'app_producto_index' => [[], ['_controller' => 'App\\Controller\\ProductoController::index'], [], [['text', '/producto']], [], [], []],
    'app_producto_new' => [[], ['_controller' => 'App\\Controller\\ProductoController::new'], [], [['text', '/producto/new']], [], [], []],
    'app_producto_show' => [['id'], ['_controller' => 'App\\Controller\\ProductoController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/producto']], [], [], []],
    'app_producto_edit' => [['id'], ['_controller' => 'App\\Controller\\ProductoController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/producto']], [], [], []],
    'app_producto_delete' => [['id'], ['_controller' => 'App\\Controller\\ProductoController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/producto']], [], [], []],
    'app_cliente_index' => [[], ['_controller' => 'App\\Controller\\ClienteController::index'], [], [['text', '/cliente']], [], [], []],
    'app_cliente_new' => [[], ['_controller' => 'App\\Controller\\ClienteController::new'], [], [['text', '/cliente/new']], [], [], []],
    'app_cliente_show' => [['id'], ['_controller' => 'App\\Controller\\ClienteController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/cliente']], [], [], []],
    'app_cliente_edit' => [['id'], ['_controller' => 'App\\Controller\\ClienteController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/cliente']], [], [], []],
    'app_cliente_delete' => [['id'], ['_controller' => 'App\\Controller\\ClienteController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/cliente']], [], [], []],
    'app_pedido_index' => [[], ['_controller' => 'App\\Controller\\PedidoController::index'], [], [['text', '/pedido']], [], [], []],
    'app_pedido_new' => [[], ['_controller' => 'App\\Controller\\PedidoController::new'], [], [['text', '/pedido/new']], [], [], []],
    'app_pedido_show' => [['id'], ['_controller' => 'App\\Controller\\PedidoController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/pedido']], [], [], []],
    'app_pedido_edit' => [['id'], ['_controller' => 'App\\Controller\\PedidoController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/pedido']], [], [], []],
    'app_pedido_delete' => [['id'], ['_controller' => 'App\\Controller\\PedidoController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/pedido']], [], [], []],
];
